//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hemmakväll
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movy
    {
        public int MovieId { get; set; }
        public string MovieName { get; set; }
        public string DirectorName { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<int> genreID { get; set; }
    
        public virtual Genre Genre { get; set; }
    }
}
